### ISSUE TITLE
 Object not found - no matching loose object

### ISSUE THREAD

**Issue by joost** [kevinjalbert/git_statistics#64] opened 2018-01-28 16:02 UTC
Installed the latest git_statistics (v0.8.0):
```
gem install git_statistics
Fetching: rugged-0.23.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rugged-0.23.3
Fetching: language_sniffer-1.0.2.gem (100%)
Successfully installed language_sniffer-1.0.2
Fetching: git_statistics-0.8.0.gem (100%)
Successfully installed git_statistics-0.8.0
3 gems installed
```

When running from the command line I get the following error:
```
git_statistics-0.8.0/lib/git_statistics/collector.rb:17:in `each': Object not found - no matching loose object
```

**Comment by kevinjalbert** [comment] 2018-01-31 01:43
@joost Are you able to provide additional information:
 - Ruby version (i.e., `ruby --version`)
 - Any options on the command?
 - Repository (if its public, that is)

I just tried a local repository using ruby 2.3.1 and 2.4.2 -- both worked without any issue. I suspect this might have to do with the internals of the repository. If its a public repository I'll dig into that.

At this point, I cannot reproduce this, so its hard to figure the exact issue.

**Comment by kevinjalbert** [comment] 2019-11-09 03:34
I'm closing this issue as a great deal of time has passed. If there is renewed interest just reopen or make a new issue and link to this one.

**Closed as completed by kevinjalbert** 2019-11-09 03:34 UTC
